# This is a basic workflow to help you get started with Actions

name: Pull Request CI/CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: echo Build id of $GITHUB_RUN_ID
      - run: npm install

      - name: Test
        run: npm test

      - name: Build -- production
        run: npm run build

      - name: Docker build of dist folder
      - run: |
        docker build --pull --rm -f "dockerfile" -t elseviercr.azurecr.io/pure-styleguide:pr "."
        docker login -u $DOCKER_CONTAINER_NAME -p $DOCKER_CONTAINER_PW elseviercr.azurecr.io
        docker push elseviercr.azurecr.io/pure-styleguide:pr
